"""
Groq LLM-Powered Biomechanical & Ergonomic Recommendation Engine.

Leverages Groq's high-speed inference API to generate personalized physical therapy,
exercise routines, posture corrections, and recovery protocols based on extracted body metrics.
"""

import json
import os
from typing import Any, Dict, List, Optional
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")


def get_default_llm_fallback(summary: Dict[str, Any], alerts: List[str]) -> Dict[str, Any]:
    """
    Fallback structured recommendation object when LLM API is unavailable.
    """
    overall_risk = summary.get("overall_risk", 0.0)
    risk_level = summary.get("risk_level", "LOW")
    
    exercises = []
    posture_tips = []
    recovery = []
    
    if summary.get("peak_knee_valgus", 0.0) > 12.0:
        exercises.append({
            "name": "Band Clamshells & Glute Bridges",
            "target_area": "Knee & Hip Abductors",
            "sets_reps": "3 sets x 15 reps",
            "description": "Strengthen gluteus medius to eliminate inward knee collapse during dynamic loading.",
            "coaching_cue": "Drive knees outward against resistance band and align knees directly over second toe."
        })
        posture_tips.append("Avoid inward collapse of knees during squatting, jumping, or stair descent.")
    
    if summary.get("landing_quality", 100.0) < 75.0:
        exercises.append({
            "name": "Soft Landings & Depth Drop Absorption",
            "target_area": "Lower Body Shock Absorption",
            "sets_reps": "3 sets x 8 drops",
            "description": "Train eccentric quad and glute loading to dissipate impact forces softly.",
            "coaching_cue": "Land quietly toe-to-heel with knee flexion approaching 60-90 degrees."
        })
        recovery.append("Allow adequate quad recovery between explosive jumping sessions.")

    if summary.get("peak_trunk_lean", 0.0) > 18.0:
        exercises.append({
            "name": "Pallof Press & Anti-Rotation Planks",
            "target_area": "Core & Lumbar Spine",
            "sets_reps": "3 sets x 30s hold",
            "description": "Build anti-flexion and anti-rotation core stability to stabilize upper torso posture.",
            "coaching_cue": "Maintain neutral spine stack over pelvis without leaning forward or lateral swaying."
        })
        posture_tips.append("Maintain an upright neutral spine stack when carrying loads or performing squat exercises.")

    if summary.get("avg_symmetry", 100.0) < 88.0:
        exercises.append({
            "name": "Single-Leg Bulgarian Split Squats",
            "target_area": "Unilateral Strength Balance",
            "sets_reps": "3 sets x 10 reps/side",
            "description": "Correct left-right bilateral strength imbalance.",
            "coaching_cue": "Focus on equal depth and weight distribution through full tripod foot contact."
        })

    if not exercises:
        exercises.append({
            "name": "Maintenance Posture & Mobility Routine",
            "target_area": "Full Body Kinematics",
            "sets_reps": "Daily 10-minute flow",
            "description": "Maintain excellent current joint alignment and baseline stability.",
            "coaching_cue": "Keep up proper movement patterns and balanced strength training."
        })
        posture_tips.append("Maintain current optimal movement mechanics and ergonomic posture.")
        recovery.append("Follow standard hydration, sleep, and progressive overload principles.")

    return {
        "engine": "Fallback Rule Engine",
        "executive_summary": f"Biomechanical risk assessment computed an overall score of {overall_risk:.1f}/100 ({risk_level} risk level). Key risk flags require targeted neuromuscular re-education and movement correction.",
        "corrective_exercises": exercises,
        "posture_and_ergonomics": posture_tips if posture_tips else ["Maintain upright posture with shoulders down and back."],
        "recovery_protocol": recovery if recovery else ["Perform 5-10 minutes of active cooldown stretching after high-intensity movement."],
        "actionable_tips": alerts if alerts else ["Movement form is currently within optimal range."]
    }


def generate_llm_recommendations(summary: Dict[str, Any], alerts: List[str]) -> Dict[str, Any]:
    """
    Generate Groq LLM-powered ergonomic and biomechanical recommendations.
    
    :param summary: Dictionary of biomechanical summary metrics.
    :param alerts: List of string alerts generated by rule assessment.
    :return: Formatted dictionary containing structured AI recommendations.
    """
    api_key = os.getenv("GROQ_API_KEY", "").strip()
    if not api_key:
        print("[Groq LLM] No API key found. Using fallback recommendation engine.")
        return get_default_llm_fallback(summary, alerts)

    try:
        from groq import Groq
        client = Groq(api_key=api_key)

        prompt = f"""
You are an expert Biomechanical Specialist, Ergonomic Consultant, and Doctor of Physical Therapy.
Analyze the following movement risk analysis data and generate structured, actionable, and personalized recommendations for the client.

=== BIOMECHANICAL METRICS ===
- Video / Subject: {summary.get('video_name', 'Analyzed Video')}
- Overall Risk Score: {summary.get('overall_risk', 0.0):.1f} / 100 (Level: {summary.get('risk_level', 'UNKNOWN')})
- Body Part Risk Scores:
  * Knee Risk: {summary.get('knee_risk', 0.0):.1f}/100
  * Hip Risk: {summary.get('hip_risk', 0.0):.1f}/100
  * Spine Risk: {summary.get('spine_risk', 0.0):.1f}/100
  * Fatigue Risk: {summary.get('fatigue_risk', 0.0):.1f}/100
- Movement Scores:
  * Landing Quality: {summary.get('landing_quality', 100.0):.1f}/100
  * Stability Score: {summary.get('stability_score', 100.0):.1f}/100
  * Bilateral Symmetry: {summary.get('avg_symmetry', 100.0):.1f}%
  * Fatigue Score: {summary.get('fatigue_score', 0.0):.1f}%
- Peak Kinematic Deviations:
  * Peak Knee Valgus Inward Collapse: {summary.get('peak_knee_valgus', 0.0):.1f}°
  * Peak Trunk Forward/Lateral Lean: {summary.get('peak_trunk_lean', 0.0):.1f}°
- Active System Alerts: {json.dumps(alerts)}

=== INSTRUCTIONS ===
Provide your response strictly in raw JSON format (without markdown codeblocks) matching the structure below:
{{
  "engine": "Groq LLM (llama-3.3-70b-versatile)",
  "executive_summary": "<Professional 2-3 sentence clinical summary of the user's overall biomechanical risk state>",
  "corrective_exercises": [
    {{
      "name": "<Exercise Name>",
      "target_area": "<Target muscle / joint group>",
      "sets_reps": "<Recommended sets & reps or duration>",
      "description": "<Detailed execution instructions>",
      "coaching_cue": "<Key mental or posture cue to remember during movement>"
    }}
  ],
  "posture_and_ergonomics": [
    "<Practical advice on daily posture, workstation setup, or movement mechanics>"
  ],
  "recovery_protocol": [
    "<Rest, mobility, stretching, or fatigue mitigation strategies>"
  ],
  "actionable_tips": [
    "<3-4 concise, high-priority bullet points for immediate action>"
  ]
}}
"""

        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": "You are a world-class biomechanics, ergonomics, and physical therapy AI assistant. Return ONLY valid raw JSON with no conversational text or markdown codeblocks."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.3,
            max_tokens=1500,
        )

        response_content = completion.choices[0].message.content.strip()

        # Clean JSON response if wrapped in markdown block
        if response_content.startswith("```json"):
            response_content = response_content[7:]
        if response_content.startswith("```"):
            response_content = response_content[3:]
        if response_content.endswith("```"):
            response_content = response_content[:-3]
        response_content = response_content.strip()

        parsed_json = json.loads(response_content)
        parsed_json["engine"] = f"Groq LLM ({GROQ_MODEL})"
        return parsed_json

    except Exception as exc:
        print(f"[Groq LLM Error] Exception during LLM generation: {exc}")
        return get_default_llm_fallback(summary, alerts)
